# Generated by Django 4.2.4 on 2025-01-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the product name', max_length=50)),
                ('brand', models.CharField(help_text='Enter the brand name', max_length=50)),
                ('description', models.TextField(help_text='Enter a description of the product')),
                ('MRP', models.IntegerField(default=0, help_text='Enter the maximum retail price')),
            ],
        ),
    ]
