# Generated by Django 4.2.4 on 2025-01-12 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
