# Generated by Django 4.2.4 on 2025-01-12 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_order_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
