# Generated by Django 4.2.4 on 2025-01-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order_orderitems'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItems',
        ),
    ]
