# Generated by Django 4.2.16 on 2025-02-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_orderitems_order_orderitems_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(help_text='Enter a description of the product', max_length=50),
        ),
    ]
