# Generated by Django 4.2.4 on 2025-01-04 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('mrp', models.IntegerField()),
                ('catagory', models.CharField(max_length=20)),
                ('material', models.CharField(max_length=10)),
                ('stock', models.IntegerField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=2)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
