# Generated by Django 4.2.4 on 2025-01-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optical_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lens',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
