# Generated by Django 4.2.4 on 2025-01-09 09:33

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optical_main', '0002_product_lens'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='catagory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mrp',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('EYEWEAR', 'Eyewear'), ('SUNGLASSES', 'Sunglasses'), ('CONTACT_LENSES', 'Contact Lenses'), ('OTHERS', 'Others')], default='Others', help_text='Select the product category', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(help_text='Enter the brand name', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(default=datetime.date.today, help_text='Enter the date of addition'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Enter a description of the product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, help_text='Enter the discount percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='lens',
            field=models.CharField(blank=True, help_text='Enter the lens type (if applicable)', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(choices=[('PLASTIC', 'Plastic'), ('METAL', 'Metal'), ('COMPOSITE', 'Composite')], help_text='Select the material', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Enter the product name', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(help_text='Enter the stock quantity', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='MRP',
            field=models.IntegerField(default=0, help_text='Enter the maximum retail price', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
