# Generated by Django 4.2.4 on 2024-12-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optical_main', '0004_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='rating',
            name='comments',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
