# Generated by Django 4.2.4 on 2025-01-09 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('optical_main', '0004_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('EYEWEAR', 'Eyewear'), ('SUNGLASSES', 'Sunglasses'), ('READING_GLASS', 'Reading Glass'), ('OTHERS', 'Others')], default='OTHERS', help_text='Select the product category', max_length=20),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter the first name', max_length=20)),
                ('last_name', models.CharField(help_text='Enter the last name', max_length=20)),
                ('email', models.EmailField(help_text='Enter the email address', max_length=50, unique=True)),
                ('phone', models.CharField(help_text='Enter the phone number', max_length=10)),
                ('address', models.TextField(help_text='Enter the address')),
                ('second_address', models.TextField(blank=True, help_text='Enter the address')),
                ('dob', models.DateField(help_text='Enter the date of birth', null=True)),
                ('userprofile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
