# Generated by Django 4.2.4 on 2025-01-09 17:37

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optical_main', '0005_alter_product_category_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0, help_text='Enter the price', validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.IntegerField(default=1, help_text='Enter the quantity', validators=[django.core.validators.MinValueValidator(0)])),
                ('date', models.DateField(default=datetime.date.today, help_text='Enter the date of order')),
                ('Payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI')], default='CASH', help_text='Select the payment mode', max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optical_main.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optical_main.product')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
