# Generated by Django 4.2.4 on 2024-12-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optical_main', '0005_rating_rating_alter_rating_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(blank=True),
        ),
    ]
