# Generated by Django 4.2.4 on 2025-01-10 01:45

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optical_main', '0006_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, help_text='Enter the rating', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(help_text='Enter the comment')),
                ('date', models.DateField(default=datetime.date.today, help_text='Enter the date')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optical_main.order')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
    ]
