# Generated by Django 4.2.4 on 2024-12-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optical_main', '0007_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='comments',
            field=models.CharField(max_length=200),
        ),
    ]
